# Set up routes for addresses in the native-routing-cidr range.
autoDirectNodeRoutes: true
bgpControlPlane:
  enabled: true
bpf:
  masquerade: false
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: dh8
containerRuntime:
  integration: containerd
endpointRoutes:
  enabled: true
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4:
  # IPv4 needed to reach github.com and ghcr.io,
  # required by Flux in order to pull repo changes.
  # https://github.com/orgs/community/discussions/10539
  enabled: true
ipv6:
  enabled: true
ipv4NativeRoutingCidr: 10.244.0.0/16
ipv6NativeRoutingCIDR: fd10:244::/64
k8sServiceHost: "::"
k8sServicePort: 7445
kubeProxyReplacement: true
# Export metrics on all IPv6 addresses.
kubeProxyReplacementHealthzBindAddr: "[::]:10256"
l2announcements:
  enabled: false # https://github.com/cilium/cilium/issues/28985
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
