# https://artifacthub.io/packages/helm/bitnami/keycloak#parameters
inputs @ {
  k,
  cluster,
  ...
}: let
  inherit (cluster) domain;
  issuer = import ../../../cert-manager/cert-manager/config/cluster-issuer.yaml.nix inputs;

  name = k.appname ./.;
  namespace = k.nsname ./.;
in rec {
  production = false; # todo

  # Use our own database.
  postgresql.enabled = false;
  # CloudNative PG managed cluster.
  externalDatabase = {
    existingSecret = "${k.fluxcd.ksname ../database}-app";
    existingSecretHostKey = "host";
    existingSecretPortKey = "port";
    existingSecretUserKey = "user";
    existingSecretDatabaseKey = "dbname";
    existingSecretPasswordKey = "password";
  };

  tls = {
    enabled = true;
    autoGenerated = true;
  };

  ingress = rec {
    enabled = true;
    ingressClassName = "nginx";
    hostname = domain;
    path = "/${name}/";
    annotations = {
      # TLS
      "cert-manager.io/cluster-issuer" = issuer.metadata.name;
      # NGINX
      "nginx.ingress.kubernetes.io/backend-protocol" = "HTTPS";
      "nginx.ingress.kubernetes.io/proxy-ssl-name" = domain;
      "nginx.ingress.kubernetes.io/proxy-ssl-secret" = "${namespace}/${name}-crt";
      "nginx.ingress.kubernetes.io/proxy-ssl-server-name" = name;
      # Homepage
      "gethomepage.dev/enabled" = "true";
      "gethomepage.dev/name" = "Keycloak";
      "gethomepage.dev/description" = "Identity management solution";
      "gethomepage.dev/group" = "Cluster Management";
      "gethomepage.dev/icon" = "keycloak.svg";
    };

    tls = true; # todo: production
    servicePort =
      if tls
      then "https"
      else "http";
  };
  proxyHeaders = "forwarded";
  httpRelativePath = ingress.path;
}
