# https://artifacthub.io/packages/helm/bitnami/keycloak#parameters
{
  k,
  cluster,
  ...
}: let
  inherit (cluster) domain;

  name = k.appname ./.;
  namespace = k.nsname ./.;
in rec {
  production = true;

  # Use our own database.
  postgresql.enabled = false;
  # CloudNative PG managed cluster.
  externalDatabase = {
    existingSecret = "${k.fluxcd.ksname ../database}-app";
    existingSecretHostKey = "host";
    existingSecretPortKey = "port";
    existingSecretUserKey = "user";
    existingSecretDatabaseKey = "dbname";
    existingSecretPasswordKey = "password";
  };

  tls = {
    enabled = true;
    autoGenerated = true;
  };

  ingress = rec {
    enabled = true;
    ingressClassName = "nginx";
    hostname = domain;
    path = "/${name}";
    annotations = {
      # TLS
      "cert-manager.io/cluster-issuer" = "letsencrypt";
      # NGINX
      # TODO: Configure mTLS between ingress controller & keycloak: https://www.keycloak.org/server/mutual-tls
      "nginx.ingress.kubernetes.io/backend-protocol" = "HTTPS";
      "nginx.ingress.kubernetes.io/proxy-ssl-name" = name;
      "nginx.ingress.kubernetes.io/proxy-ssl-secret" = "${namespace}/${name}-crt";
      "nginx.ingress.kubernetes.io/proxy-ssl-server-name" = "on";
      "nginx.ingress.kubernetes.io/proxy-ssl-verify" = "on";
      # Homepage
      "gethomepage.dev/enabled" = "true";
      "gethomepage.dev/name" = "Keycloak";
      "gethomepage.dev/description" = "Identity provider";
      "gethomepage.dev/group" = "Cluster Management";
      "gethomepage.dev/icon" = "${name}.svg";
      "gethomepage.dev/href" = "/${name}/realms/dornhaus/account";
    };

    tls = production;
    servicePort =
      if tls
      then "https"
      else "http";
  };
  proxyHeaders = "forwarded";
  httpRelativePath = "${ingress.path}/";
}
