key_groups: &keys
- age:
  - age10svcxhp982lemvu7xxnvmqtmuxemyjt5qh9k0qw38e9j694vyd5shsn3ym

creation_rules:
- path_regex: ansible/.*\.sops\.yaml
  encrypted_regex: "^(root_password|secret)$"
  key_groups: *keys
- path_regex: talos/.*\.sops\.yaml
  key_groups: *keys
- path_regex: k8s/.*\.sops\.yaml
  encrypted_regex: "^stringData$"
  key_groups: *keys
- path_regex: jh/.*\.sops\.conf
  encrypted_regex: "^PrivateKey$"
  key_groups: *keys

stores:
  yaml:
    indent: 2
