---
formatter:
  eof_newline: true
  include_document_start: true
  indent: 2
  indentless_arrays: true
  line_ending: lf
  pad_line_comments: 1
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
