---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitlab-dh8
  namespace: flux-system
spec:
  interval: 30m
  url: https://gitlab.com/attilaolah/dh8
  ref:
    branch: main
  ignore: |
    # ignore all
    /*
    # include kubernetes directory
    !/k8s
    # ignore kubernetes bootstrap files
    /k8s/flux/bootstrap/*
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./k8s/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: gitlab-dh8
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
