---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx
  namespace: flux-system
spec:
  targetNamespace: ingress-nginx
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./ingress-nginx/ingress-nginx/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
