---
autoDirectNodeRoutes: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
endpointRoutes:
  enabled: true
externalIPs:
  enabled: true
hubble:
  enabled: false
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.244.0.0/16
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: fd10:244::/56
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: '[::]:10256'
l2announcements:
  enabled: true
loadBalancer:
  acceleration: best-effort
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
