---
- name: Set HTTPS repository mirrors
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: https://dl-cdn.alpinelinux.org/alpine/{{ alpine_version }}/{{ item }}
    state: present
  loop:
  - main
  - community

- name: Remove HTTP repository mirrors
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    regexp: ^http://
    state: absent

- name: Update APK packages
  community.general.apk:
    available: true
    update_cache: true
    upgrade: true
  register: updates

- name: Reboot after a kernel upgrade
  when: "'linux-lts' in updates.packages"
  ansible.builtin.reboot:
  throttle: 1
