---
- name: Set repository mirror
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: http://dl-cdn.alpinelinux.org/alpine/{{ alpine_version }}/community
    state: present

- name: Update APK packages
  community.general.apk:
    available: true
    update_cache: true
    upgrade: true
  register: updates

- name: Reboot after a kernel upgrade
  when: "'linux-lts' in updates.packages"
  ansible.builtin.reboot:
  throttle: 1
