- name: Configure storage
  when: zfs
  import_tasks: configure_zfs.yaml
  become: true

- name: Add ZFS services to boot runlevel
  when: zfs
  ansible.builtin.service:
    name: zfs-{{ item }}
    enabled: true
    runlevel: boot
  loop:
  - load-key
  - import
  - mount
