---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: flux
  secretRef:
    name: flux-system
  url: ssh://git@github.com/attilaolah/homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
