---
- name: Install ZFS tools
  community.general.apk:
    name:
    - lsblk
    - zfs
    - zfs-lts
    state: present

- name: Load ZFS module
  community.general.modprobe:
    name: zfs
    state: present
