---
clusterName: &cluster dh8
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.2
endpoint: https://192.168.8.1:6443
domain: dorn.haus
cniConfig:
  name: none
additionalApiServerCertSans: &sans
  - "::1"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: k8s-01
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: 192.168.8.1
  - hostname: k8s-06
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: 192.168.8.6
  - hostname: k8s-07
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: 192.168.8.7

patches:
  - |-
    cluster:
      network:
        podSubnets:
          # IPv6-only:
          - fd10:244::/64
        serviceSubnets:
          # IPv6-only:
          - fd10:96::/108
      proxy:
        # Disable kube-proxy, since we're using
        # Cilium's kube-proxy replacement functionality.
        disabled: true
      controllerManager:
        extraArgs:
          # Prefer IPv6:
          bind-address: "::1"
      scheduler:
          extraArgs:
            # Prefer IPv6:
            bind-address: "::1"
    machine:
      time:
        servers:
        # IPv6-enabled:
        - time.cloudflare.com
      network:
        nameservers:
          - 2606:4700:4700::1001
          - 2001:4860:4860::8844
          - 1.0.0.1
          - 8.8.4.4
