---
clusterName: &cluster dh8
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.2
endpoint: https://[2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2]:6443
domain: k8s.dorn.haus
cniConfig:
  name: none
additionalApiServerCertSans: &sans
  - "::"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: 01.k8s.dorn.haus
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: 2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2
    nameservers:
      - 2606:4700:4700::1001
      - 2001:4860:4860::8844
      - 2606:4700:4700::1111
      - 2001:4860:4860::8888
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "*"
        dhcp: false

patches:
  - |-
    cluster:
      network:
        podSubnets:
          - fd10:244::/64
        serviceSubnets:
          - fd10:96::/108
      proxy:
        disabled: true
      controllerManager:
        extraArgs:
          bind-address: "::"
      scheduler:
          extraArgs:
            bind-address: "::"
    machine:
      time:
        servers:
        - time.cloudflare.com
