---
clusterName: &cluster dh8
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.1
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.0
endpoint: https://[2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2]:6443
domain: k8s.dorn.haus
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: 01.k8s.dorn.haus
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: 2001:171b:c9b8:8d40:ee8e:b5ff:fe6f:41d2
    nameservers:
      - 2606:4700:4700::1001
      - 2606:4700:4700::1111

patches:
  - |-
    machine:
      time:
        servers:
        - time.cloudflare.com
