---
clusterName: &cluster dh8
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.2
endpoint: https://192.168.8.1:6443
domain: dorn.haus
cniConfig:
  name: none
additionalApiServerCertSans: &sans
  - "::"
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: k8s-01
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: fd10:8::1
    nameservers:
      - 1.0.0.1
      - 8.8.4.4
      - 2606:4700:4700::1001
      - 2001:4860:4860::8844
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "*"
        dhcp: true
        mtu: 1500

patches:
  - |-
    cluster:
      network:
        podSubnets:
          # IPv6-only:
          - fd10:244::/64
        serviceSubnets:
          # IPv6-only:
          - fd10:96::/108
      proxy:
        disabled: true
      controllerManager:
        extraArgs:
          # Prefer IPv6:
          bind-address: "::"
      scheduler:
          extraArgs:
            # Prefer IPv6:
            bind-address: "::"
    machine:
      time:
        servers:
        # IPv6-enabled:
        - time.cloudflare.com
