---
clusterName: dh8
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.6.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.29.2
endpoint: https://[fd10:8::1]:6443
domain: dorn.haus
cniConfig:
  name: none
additionalApiServerCertSans: &sans
  - "::"  # api-server
  - "::1" # controller-manager, scheduler
additionalMachineCertSans: *sans
allowSchedulingOnControlPlanes: true

nodes:
  - hostname: k8s-01
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: fd10:8::1
    networkInterfaces:
    - deviceSelector:
        hardwareAddr: "*"
      addresses:
        - fd10:8::1/64
      routes:
        - network: fd10:8::/64
      dhcp: false
  - hostname: k8s-06
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: fd10:8::6
    networkInterfaces:
    - deviceSelector:
        hardwareAddr: "*"
      addresses:
        - fd10:8::6/64
      routes:
        - network: fd10:8::/64
      dhcp: false
  - hostname: k8s-07
    installDisk: /dev/sda
    controlPlane: true
    ipAddress: fd10:8::7
    networkInterfaces:
    - deviceSelector:
        hardwareAddr: "*"
      addresses:
        - fd10:8::7/64
      routes:
        - network: fd10:8::/64
      dhcp: false

patches:
  - |-
    cluster:
      network:
        podSubnets:
          # IPv6-only:
          - fd10:244::/64
        serviceSubnets:
          # IPv6-only:
          - fd10:96::/108
      proxy:
        # Disable kube-proxy, since we're using
        # Cilium's kube-proxy replacement functionality.
        disabled: true
      apiServer:
        extraArgs:
          # Prefer IPv6 all interfaces.
          # TODO: Set up firewall rules to make sure this is not accessible
          # through the external interfaces (via the IPv6 pinholing setup.)
          bind-address: "::"
      controllerManager:
        extraArgs:
          # Prefer IPv6 loopback:
          bind-address: "::1"
      scheduler:
          extraArgs:
            # Prefer IPv6 loopback:
            bind-address: "::1"
    machine:
      time:
        servers:
        # IPv6-enabled:
        - time.cloudflare.com
      network:
        nameservers:
          - 2606:4700:4700::1001
          - 2001:4860:4860::8844
        extraHostEntries:
          - ip: fd10:8::1:1
            aliases:
              - jh
              - jh.dorn.haus
      env:
        http_proxy: &proxy "jh:3128"
        https_proxy: *proxy
