---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # TODO: Merge from //talos/apps/cilium-values.yaml.
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
    ipMasqAgent:
      enabled: true
    bgpControlPlane:
      enabled: false
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      id: 1
      name: dh8
    containerRuntime:
      integration: containerd
    endpointRoutes:
      enabled: true
    hubble:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4:
      # IPv4 needed to reach github.com and ghcr.io,
      # required by Flux in order to pull repo changes.
      # https://github.com/orgs/community/discussions/10539
      enabled: true
    ipv6:
      enabled: true
    ipv4NativeRoutingCidr: 10.244.0.0/16
    ipv6NativeRoutingCIDR: fd10:244::/64
    k8sServiceHost: "::"
    k8sServicePort: 7445
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: "[::]:10256"
    l2announcements:
      enabled: false # https://github.com/cilium/cilium/issues/28985
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      replicas: 1
      rollOutPods: true
# NEW: vvvvvv
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
# NEW: ^^^^^^
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
