---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configure hosts file
  ansible.builtin.copy:
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
    content: |
      127.0.0.1 localhost {{ inventory_hostname }} localhost.dorn.haus {{ inventory_hostname }}.dorn.haus
      ::1       localhost {{ inventory_hostname }} localhost.dorn.haus {{ inventory_hostname }}.dorn.haus

- name: Update /etc/network/interfaces
  ansible.builtin.template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true

- name: Update /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
