---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configure hosts file
  ansible.builtin.copy:
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
    content: |
      127.0.0.1 localhost {{ inventory_hostname }} localhost.dorn.haus {{ inventory_hostname }}.dorn.haus
      ::1       localhost {{ inventory_hostname }} localhost.dorn.haus {{ inventory_hostname }}.dorn.haus

- name: Configure network interfaces
  when: ansible_facts["os_family"]|lower == "alpine"
  vars:
    ipv4:
      addr: 192.168.4.1/16
      gateway: 192.168.1.1
      nameservers:
      - 1.0.0.1
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
    ipv6:
      addr: fd10:8::ba27:ebff:fe69:d702/64
      gateway: fe80::924d:4aff:fecc:ef8b
      nameservers:
      - 2001:4860:4860::8844
      - 2001:4860:4860::8888
      - 2606:4700:4700::1001
      - 2606:4700:4700::1111
  ansible.builtin.template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true

- name: Install Tailscale
  when: ansible_facts["os_family"]|lower == "alpine"
  community.general.apk:
    name: tailscale
    update_cache: true

- name: Start Tailscale service
  ansible.builtin.service:
    name: tailscale
    state: started
    enabled: true

- name: Join Tailscale network
  ansible.builtin.command:
    argv:
    - tailscale
    - up
    - --authkey={{ secrets.tailscale.ephemeral_key.secret }}
    - --hostname={{ inventory_hostname }}
    - --ssh
