---
- name: Install Tailscale
  when: ansible_facts["os_family"] | lower == "alpine"
  community.general.apk:
    name: tailscale
    update_cache: true

- name: Start Tailscale service
  ansible.builtin.service:
    name: tailscale
    state: started
    enabled: true

- name: Check Tailscale status
  ansible.builtin.command:
    argv:
    - tailscale
    - status
    - --peers=false
    - --self
    - --json
  register: tailscale_status
  changed_when: false
  until: tailscale_status.rc == 0
  retries: 8
  delay: 3

- name: Join Tailscale network if needed
  when: not (tailscale_status.stdout | ansible.builtin.from_json).Self.Online
  ansible.builtin.command:
    argv:
    - tailscale
    - up
    - --authkey={{ secrets.tailscale.ephemeral_key.secret }}
    - --hostname={{ inventory_hostname }}
    - --accept-routes=false
    - --accept-dns=false
    - --ssh

- name: Configure IPv4/IPv6 forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
  loop:
  - net.ipv4.ip_forward
  - net.ipv6.conf.all.forwarding
