---
- name: Bootstrap Alpine nodes
  hosts: alpine
  # Gathering facts requires Python which might not be installed yet.
  gather_facts: false
  roles:
  - bootstrap

- name: Setup / Update Alpine nodes
  hosts: alpine
  become: true
  # Gathering facts fails due to a bug on locker-11, hence disabled here.
  gather_facts: false
  become_method: doas
  roles:
  - role: network
    tags: [network]
  - role: packages
    tags: [update]
  - role: storage
    tags: [storage]
