---
- name: Bootstrap Alpine nodes
  hosts: alpine
  # Gathering facts requires Python which might not be installed yet.
  gather_facts: false
  roles:
  - bootstrap

- name: Setup / Update Alpine nodes
  hosts: alpine
  become: true
  gather_facts: false
  become_method: doas
  roles:
  - configure_network
  - update_packages
