- name: Enable IPv4 route_localnet
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: "1"
    state: present
    reload: yes

- name: Configure nftables
  ansible.builtin.template:
    src: etc/nftables.nft
    dest: /etc/nftables.nft
    backup: true
  notify:
  - Apply nftables configuration
