- name: Enable cgroups
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: '^#?\s*rc_cgroup_mode='
    line: 'rc_cgroup_mode="unified"'
    backrefs: true

- name: Enable and start cgroups service
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
  - cgroups
  - dbus

- name: Add udev services to sysinit runlevel
  ansible.builtin.service:
    name: "{{ item }}"
    runlevel: sysinit
    enabled: true
  loop:
  - udev
  - udev-trigger
  - udev-settle
  register: udev_services
