---
name: Build

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build Flux manifests
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes

    - name: Detect version
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Write version to version.txt file
      run: |
        echo "${{ steps.ghd.outputs.describe }}" > version.txt

    - name: Upload version artifact
      uses: actions/upload-artifact@v4
      with:
        name: version
        path: version.txt
        if-no-files-found: error
        compression-level: 0
        retention-days: 2

    - name: Build manifests archive
      id: build
      run: |
        echo -n artifact_dir= >> "$GITHUB_OUTPUT"
        nix build --print-out-paths | tee -a "$GITHUB_OUTPUT"

    - name: Upload manifests artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifests
        path: ${{ steps.build.outputs.artifact_dir }}
        if-no-files-found: error
        compression-level: 9
        retention-days: 2

  deploy_test:
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - name: Download manifests archive
      uses: actions/download-artifact@v5

    - name: debug
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        echo ---
        find $GITHUB_WORKSPACE
        echo ---
        find .

    - name: Detect artifact dir and version
      id: artifact
      run: |
        echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
