---
name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Manifests
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes

    - name: Check Nix flake
      run: nix flake check --impure

    - name: Build manifests archive
      run: |
        echo -n artifact_dir= >> $GITHUB_ENV
        nix build --print-out-paths | tee -a $GITHUB_ENV

    - name: Detect artifact version
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifests-${{ steps.ghd.outputs.describe }}
        path: ${{ env.artifact_dir }}
        if-no-files-found: error
        compression-level: 9  # already compressed
        retention-days: 8
