---
name: Build & Check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Flux Manifests
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # For SonarQube:
        # Shallow clones should be disabled for a better relevancy of analysis.
        # Still, don't pull the entire history as it is likely unnecessary; just pull the last couple commits.
        fetch-depth: 100

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        install_url: https://nixos.org/nix/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes

    - name: Check Nix flake
      run: nix flake check --impure

    - name: Build manifests archive
      id: build
      run: |
        echo -n artifact_dir= >> "$GITHUB_OUTPUT"
        nix build --print-out-paths | tee -a "$GITHUB_OUTPUT"

    - name: Extract manifests from archive
      run: |
        cp -rf "${{ steps.build.outputs.artifact_dir }}"/* manifests

    - name: Detect artifact version
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Set SonarQube project version
      run: |
        echo "sonar.projectVersion=${{ steps.ghd.outputs.describe }}" >> sonar-project.properties

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifests-${{ steps.ghd.outputs.describe }}
        path: ${{ steps.build.outputs.artifact_dir }}
        if-no-files-found: error
        compression-level: 9
        retention-days: 8
