---
name: Quality Analysis

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  sonarqube:
    name: Run SonarQube scan
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        # Shallow clones should be disabled for a better relevancy of analysis.
        fetch-depth: 0

    - name: Run SonarQube scan
      uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
