---
name: Quality Analysis

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  sonarqube:
    name: Run SonarQube scan
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        # Shallow clones should be disabled for a better relevancy of analysis.
        fetch-depth: 0

    - name: Run SonarQube scan
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
