---
name: Quality Analysis

on:
  workflow_run:
    workflows:
    - Build
    types:
    - completed

env:
  OCI_REPO: oci://ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}

jobs:
  sonarqube:
    name: SonarQube
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Shallow clones should be disabled for a better relevancy of analysis.
        fetch-depth: 0

    - name: Download manifests archive
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract manifests from archive
      run: |
        mkdir build
        mv manifests-* build/manifests

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
